---
- name: install docker (Debian/Ubuntu)
  block:
    - name: apt update
      apt:
        upgrade: dist
        update_cache: yes

    - name: install docker components
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg-agent
          - software-properties-common
        state: latest
    

    - name: Add Docker apt key
      shell: "curl -sSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -"
      args:
        warn: no

    - name: Add Docker repository
      apt_repository:
        repo: "deb [arch=amd64] https://download.docker.com/linux/{{ ansible_distribution|lower }} {{ ansible_distribution_release }} stable"
        state: present
        update_cache: yes

    - name: apt update
      apt:
        upgrade: dist
        update_cache: yes

    - name: install docker-ce
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io

  when: (ansible_distribution == "Ubuntu" and ansible_distribution_release == "eoan" and ansible_distribution_major_version >= '19.10') or
        (ansible_distribution == "Ubuntu" and ansible_distribution_release == "bionic" and ansible_distribution_major_version >= '18.04') or
        (ansible_distribution == "Ubuntu" and ansible_distribution_release == "xenial" and ansible_distribution_major_version >= '16.04')