---
- name: install docker (Debian/Ubuntu)
  block:
    - name: apt update
      apt:
        upgrade: dist
        update_cache: yes

    - name: install docker components
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg-agent
          - software-properties-common
        state: latest
    
    - name: add Docker GPG key
      command: curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -

    - name: add docker repository
      command: "deb [arch=amd64] https://download.docker.com/linux/ubuntu \
                $(lsb_release -cs) \
                stable"

    - name: apt update
      apt:
        upgrade: dist
        update_cache: yes

    - name: install docker-ce
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io

  when: (ansible_distribution == "Ubuntu" and ansible_distribution_release == "Eoan" and ansible_distribution_major_version >= '19.10') or
        (ansible_distribution == "Ubuntu" and ansible_distribution_release == "Bionic" and ansible_distribution_major_version >= '18.04') or
        (ansible_distribution == "Ubuntu" and ansible_distribution_release == "Xenial" and ansible_distribution_major_version >= '16.04')