---
- name: install docker (Debian/Ubuntu)
  block:
    - name: apt update
      apt:
        upgrade: dist
        update_cache: yes

    - name: install docker components
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg-agent
          - software-properties-common
        state: latest
    
    - name: add Docker GPG key
      command: curl -fsSL https://download.docker.com/linux/debian/gpg | apt-key add -
        warn: false

    - name: add docker repository
      command: "deb [arch=amd64] https://download.docker.com/linux/debian \
                $(lsb_release -cs) \
                stable"

    - name: apt update
      apt:
        upgrade: dist
        update_cache: yes

    - name: install docker-ce
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io

  when: (ansible_distribution == "Debian" and ansible_distribution_release == "buster" and ansible_distribution_major_version >= '10') or 
        (ansible_distribution == "Debian" and ansible_distribution_release == "stretch" and ansible_distribution_major_version >= '9')
